import { useState } from "react";
import { ArrowRight, CheckCircle2, Leaf, MapPin, Route, ShieldCheck, Sprout, Truck, Users } from "lucide-react";
import { Link } from "wouter";
import { ActionButton, AlertBanner, BadgePill, Eyebrow, LoadingPanel, PageHeader, Surface } from "@/components/farmconnect/DesignSystem";
import { trpc } from "@/lib/trpc";
import { demoBuyers, demoFarmers } from "@/data/demoData";

function money(value: number) { return `₹${Math.round(value).toLocaleString("en-IN")}`; }

export default function Demo() {
  const [perspective, setPerspective] = useState<"farmer" | "buyer">("farmer");
  const [farmerIndex, setFarmerIndex] = useState(0);
  const [buyerIndex, setBuyerIndex] = useState(0);
  const [farmerQuantity, setFarmerQuantity] = useState(850);
  const [buyerQuantity, setBuyerQuantity] = useState(1000);
  const explore = trpc.demo.explore.useQuery({ farmerIndex, buyerIndex, farmerQuantity, buyerQuantity });
  const data = explore.data;

  return <div className="container py-8 sm:py-12">
    <div className="sticky top-3 z-10 mb-8 flex flex-col gap-4 rounded-[22px] border border-[#e6d7b9] bg-[#fff9ea]/95 p-5 shadow-sm backdrop-blur sm:flex-row sm:items-center sm:justify-between">
      <div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#f3dfaa] text-[#856117]"><ShieldCheck size={18} /></span><div><div className="text-xs font-bold uppercase tracking-[0.16em] text-[#856117]">DEMO MODE · SAMPLE DATA</div><p className="mt-1 text-sm leading-6 text-[#6f5b31]">Interactive walkthrough. Every change is temporary, local to this demo, and never saved.</p></div></div>
      <Link href="/login" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-[#856117] hover:text-[#5f481c]">Return to sign in <ArrowRight size={15} /></Link>
    </div>

    <PageHeader eyebrow="DEMO / COMPLETE WALKTHROUGH" title="Explore the FarmConnect decision journey." description="Switch between Farmer and Buyer perspectives, adjust sample quantities, and see matching, logistics, market context, and aggregation update from deterministic demo calculations." />

    <div className="mt-8 flex flex-wrap gap-2 rounded-2xl border border-[#e5ecdf] bg-white p-2">
      {([["farmer", "Farmer Demo", Sprout], ["buyer", "Buyer Demo", Users]] as const).map(([value, label, Icon]) => <button key={value} type="button" onClick={() => setPerspective(value)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${perspective === value ? "bg-[#1b5e3c] text-white" : "text-[#496454] hover:bg-[#eff8e9]"}`}><Icon size={16} />{label}</button>)}
      <div className="ml-auto hidden items-center gap-2 px-3 text-xs font-semibold text-[#819087] md:flex"><CheckCircle2 size={14} className="text-[#6f9b63]" />No production API mutations</div>
    </div>

    {!data || explore.isLoading ? <div className="mt-8"><LoadingPanel label="Calculating the demo path…" /></div> : <>
      <div className="mt-8 grid gap-5 md:grid-cols-4">
        <Surface className="p-5"><div className="text-xs font-bold uppercase tracking-[0.12em] text-[#819087]">Sample location</div><div className="mt-2 font-bold text-[#18332a]">{perspective === "farmer" ? data.selectedFarmer.location.city : data.selectedBuyer.location.city}</div><div className="mt-1 text-xs text-[#718274]">Demo mapping only</div></Surface>
        <Surface className="p-5"><div className="text-xs font-bold uppercase tracking-[0.12em] text-[#819087]">Crop</div><div className="mt-2 font-bold text-[#18332a]">{data.requirement.crop}</div><div className="mt-1 text-xs text-[#718274]">Sample market context</div></Surface>
        <Surface className="p-5"><div className="text-xs font-bold uppercase tracking-[0.12em] text-[#819087]">Compatible paths</div><div className="mt-2 font-bold text-[#28623f]">{data.matches.matches.length}</div><div className="mt-1 text-xs text-[#718274]">Deterministic matches</div></Surface>
        <Surface className="p-5"><div className="text-xs font-bold uppercase tracking-[0.12em] text-[#819087]">Aggregation</div><div className="mt-2 font-bold text-[#28623f]">{data.aggregation.recommendedPlan ? `${data.aggregation.recommendedPlan.fulfilmentPercent}%` : "—"}</div><div className="mt-1 text-xs text-[#718274]">Potential fulfilment</div></Surface>
      </div>

      <div className="mt-8 grid gap-7 lg:grid-cols-[0.78fr_1.22fr] lg:items-start">
        <Surface className="p-6 sm:p-7">
          <Eyebrow icon={perspective === "farmer" ? <Sprout size={14} /> : <Users size={14} />}>{perspective === "farmer" ? "FARMER DEMO CONTROLS" : "BUYER DEMO CONTROLS"}</Eyebrow>
          <h2 className="mt-2 text-2xl font-bold tracking-[-0.04em] text-[#18332a]">Change the scenario</h2>
          <p className="mt-2 text-sm leading-6 text-[#718274]">These controls update a temporary sample calculation. They never create, update, or delete a production record.</p>
          <label className="mt-6 block text-sm font-semibold text-[#496454]">{perspective === "farmer" ? "Sample farmer" : "Sample buyer requirement"}<select value={perspective === "farmer" ? farmerIndex : buyerIndex} onChange={event => perspective === "farmer" ? setFarmerIndex(Number(event.target.value)) : setBuyerIndex(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-[#dfe9d9] bg-white px-3.5 py-3 text-[#18332a] outline-none focus:border-[#6f9b63] focus:ring-4 focus:ring-[#eff8e9]">{(perspective === "farmer" ? demoFarmers : demoBuyers).map((item, index) => <option key={item.id} value={index}>{item.name} · {"primaryCrop" in item ? item.primaryCrop : item.requiredCrop}</option>)}</select></label>
          <label className="mt-4 block text-sm font-semibold text-[#496454]">{perspective === "farmer" ? "Available quantity" : "Required quantity"}<div className="relative mt-2"><input type="number" min="1" step="50" value={perspective === "farmer" ? farmerQuantity : buyerQuantity} onChange={event => perspective === "farmer" ? setFarmerQuantity(Math.max(1, Number(event.target.value))) : setBuyerQuantity(Math.max(1, Number(event.target.value)))} className="w-full rounded-xl border border-[#dfe9d9] bg-white px-3.5 py-3 pr-14 text-[#18332a] outline-none focus:border-[#6f9b63] focus:ring-4 focus:ring-[#eff8e9]" /><span className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-xs font-semibold text-[#819087]">kg</span></div></label>
          <div className="mt-6 rounded-2xl bg-[#f7fbf3] p-4"><div className="flex items-start gap-3"><MapPin size={17} className="mt-0.5 shrink-0 text-[#6b8f60]" /><div><div className="text-sm font-bold text-[#294c38]">Demo location intelligence</div><p className="mt-1 text-xs leading-5 text-[#718274]">Distances use the existing sample coordinates and demo mapping. FarmConnect does not request your browser location.</p></div></div></div>
          <div className="mt-5 flex flex-wrap gap-2"><ActionButton href="/how-it-works" variant="secondary" size="sm">How it works <ArrowRight size={14} /></ActionButton><ActionButton href="/about" variant="secondary" size="sm">About / Impact <ArrowRight size={14} /></ActionButton></div>
        </Surface>

        <div className="space-y-6">
          {perspective === "farmer" ? <>
            <Surface className="p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><Eyebrow icon={<Sprout size={14} />}>FARMER · SAMPLE LISTING</Eyebrow><h2 className="mt-2 text-2xl font-bold text-[#18332a]">{data.selectedFarmer.name}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-[#718274]"><MapPin size={14} />{data.selectedFarmer.village}, {data.selectedFarmer.location.city} · Sample farmer</p></div><BadgePill tone="amber">Demo only</BadgePill></div><div className="mt-6 grid gap-3 sm:grid-cols-4"><div><div className="text-xs text-[#819087]">Crop</div><div className="mt-1 font-bold text-[#294c38]">{data.listing.crop}</div></div><div><div className="text-xs text-[#819087]">Quantity</div><div className="mt-1 font-bold text-[#294c38]">{data.listing.quantityKg.toLocaleString()} kg</div></div><div><div className="text-xs text-[#819087]">Minimum</div><div className="mt-1 font-bold text-[#28623f]">₹{data.listing.minimumPricePerKg}/kg</div></div><div><div className="text-xs text-[#819087]">Location</div><div className="mt-1 font-bold text-[#294c38]">{data.listing.city}</div></div></div></Surface>
            <section><div className="mb-4 flex items-end justify-between gap-3"><div><Eyebrow icon={<Route size={14} />}>SMART MATCHING · DEMO RESULTS</Eyebrow><h2 className="mt-2 text-2xl font-bold text-[#18332a]">Buyer paths ranked by outcome</h2></div><BadgePill tone="green">Deterministic</BadgePill></div>{data.matches.matches.length === 0 ? <AlertBanner tone="warning">No sample buyer meets this listing’s crop and minimum-price rules.</AlertBanner> : <div className="space-y-4">{data.matches.matches.map(match => <Surface key={match.buyer.id} className={match.recommendation === "recommended" ? "border-[#aace94] bg-[#fbfef8] p-5" : "p-5"}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2">{match.recommendation === "recommended" && <BadgePill tone="green"><CheckCircle2 size={13} /> Recommended</BadgePill>}<BadgePill tone="amber">Sample buyer</BadgePill></div><h3 className="mt-3 text-lg font-bold text-[#18332a]">{match.buyer.name}</h3><p className="mt-1 text-xs text-[#718274]">{match.buyer.location.city} · {match.buyer.buyerType}</p></div><div className="rounded-xl bg-[#18332a] px-3 py-2 text-right text-white"><div className="text-[10px] uppercase text-[#b9d7a1]">Score</div><div className="text-xl font-bold">{match.matchScore}</div></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><div className="text-xs text-[#819087]">Distance</div><div className="mt-1 font-bold text-[#294c38]">{match.distance.distanceKm} km</div></div><div><div className="text-xs text-[#819087]">Transport</div><div className="mt-1 font-bold text-[#294c38]">{money(match.estimatedTransportCost)}</div></div><div><div className="text-xs text-[#819087]">Gross</div><div className="mt-1 font-bold text-[#294c38]">{money(match.grossRevenue)}</div></div><div><div className="text-xs text-[#819087]">Estimated net</div><div className="mt-1 font-bold text-[#28623f]">{money(match.estimatedNetOutcome)}</div></div></div><div className="mt-4 rounded-xl bg-[#f7fbf3] p-3 text-xs leading-5 text-[#5f7465]"><strong className="text-[#294c38]">Why this path?</strong> {match.explanationData.tradeoffNote}</div></Surface>)}</div>}</section>
          </> : <>
            <Surface className="p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><Eyebrow icon={<Users size={14} />}>BUYER · SAMPLE REQUIREMENT</Eyebrow><h2 className="mt-2 text-2xl font-bold text-[#18332a]">{data.selectedBuyer.name}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-[#718274]"><MapPin size={14} />{data.selectedBuyer.location.city} · {data.selectedBuyer.buyerType} · Sample buyer</p></div><BadgePill tone="amber">Demo only</BadgePill></div><div className="mt-6 grid gap-3 sm:grid-cols-4"><div><div className="text-xs text-[#819087]">Needs</div><div className="mt-1 font-bold text-[#294c38]">{data.requirement.crop}</div></div><div><div className="text-xs text-[#819087]">Quantity</div><div className="mt-1 font-bold text-[#294c38]">{data.requirement.requiredQuantityKg.toLocaleString()} kg</div></div><div><div className="text-xs text-[#819087]">Offer</div><div className="mt-1 font-bold text-[#28623f]">₹{data.requirement.offeredPricePerKg}/kg</div></div><div><div className="text-xs text-[#819087]">Market</div><div className="mt-1 font-bold text-[#294c38]">{data.aggregation.marketReference?.modalPrice ? money(data.aggregation.marketReference.modalPrice) : "Demo"}</div></div></div></Surface>
            <section><div className="mb-4 flex items-end justify-between gap-3"><div><Eyebrow icon={<Truck size={14} />}>SUPPLY · DEMO RESULTS</Eyebrow><h2 className="mt-2 text-2xl font-bold text-[#18332a]">Compatible farmer supply</h2></div><BadgePill tone="green">{data.aggregation.candidateCount} compatible</BadgePill></div><div className="space-y-3">{data.supply.map(item => <Surface key={item.farmer.id} className={item.compatible ? "border-[#aace94] bg-[#fbfef8] p-5" : "p-5 opacity-75"}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2">{item.compatible && <BadgePill tone="green">Compatible</BadgePill>}<BadgePill tone="amber">Sample farmer</BadgePill></div><h3 className="mt-3 font-bold text-[#18332a]">{item.farmer.name}</h3><p className="mt-1 text-xs text-[#718274]">{item.farmer.location.city} · {item.farmer.primaryCrop}</p></div><div className="text-right"><div className="text-xs text-[#819087]">Matched supply</div><div className="mt-1 text-xl font-bold text-[#28623f]">{item.matchedQuantityKg.toLocaleString()} kg</div></div></div><div className="mt-4 flex flex-wrap gap-4 text-xs text-[#5f7465]"><span>{item.distanceKm} km demo distance</span><span>{money(item.estimatedTransportCost)} transport estimate</span><span>Minimum ₹{item.expectedPricePerKg}/kg</span></div><p className="mt-3 text-xs leading-5 text-[#718274]">{item.compatibilityReason}</p></Surface>)}</div></section>
          </>}

          <Surface className="border-l-4 border-l-[#b9653e] p-6"><div className="flex items-start gap-3"><Users size={18} className="mt-0.5 shrink-0 text-[#b9653e]" /><div className="w-full"><Eyebrow icon={<Route size={14} />}>AGGREGATION · DEMO OPPORTUNITY</Eyebrow>{data.aggregation.recommendedPlan ? <><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><h2 className="text-xl font-bold text-[#18332a]">{data.aggregation.recommendedPlan.plannedQuantityKg.toLocaleString()} / {data.aggregation.recommendedPlan.requiredQuantityKg.toLocaleString()} kg potential fulfilment</h2><div className="text-lg font-bold text-[#28623f]">{money(data.aggregation.recommendedPlan.estimatedNetOutcome)} net estimate</div></div><p className="mt-2 text-sm leading-6 text-[#5f7465]">{data.aggregation.recommendedPlan.contributingFarmerCount} sample farmer contribution{data.aggregation.recommendedPlan.contributingFarmerCount === 1 ? "" : "s"} · {data.aggregation.recommendedPlan.fulfilmentType} fulfilment · {money(data.aggregation.recommendedPlan.transportCost)} shared logistics estimate.</p><div className="mt-4 space-y-2">{data.aggregation.recommendedPlan.contributions.map(contribution => <div key={contribution.farmerListingId} className="flex items-center justify-between rounded-xl bg-[#f7fbf3] px-3 py-2 text-xs"><span className="font-semibold text-[#294c38]">Sample listing #{contribution.farmerListingId}</span><span className="text-[#718274]">{contribution.contributedQuantityKg.toLocaleString()} kg · {contribution.distanceKm} km estimate</span></div>)}</div></> : <p className="mt-2 text-sm leading-6 text-[#718274]">No compatible collective fulfilment plan is available for this sample scenario.</p>}<div className="mt-4 rounded-xl bg-[#fff9ea] p-3 text-xs leading-5 text-[#6f5b31]">Demo mode — this calculated plan is temporary and will not be saved.</div></div></div></Surface>
        </div>
      </div>

      <Surface className="mt-8 p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><Eyebrow icon={<Leaf size={14} />}>MARKET CONTEXT · SAMPLE DATA</Eyebrow><h2 className="mt-2 text-xl font-bold text-[#18332a]">Reference prices, not live quotes</h2><p className="mt-1 text-sm text-[#718274]">{data.aggregation.marketReference?.message ?? "Demo market reference for the selected crop and location."}</p></div><BadgePill tone="amber">DEMO MARKET</BadgePill></div>{data.aggregation.marketReference && <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#f7fbf3] p-4"><div className="text-xs text-[#819087]">Min reference</div><div className="mt-1 font-bold text-[#294c38]">{money(data.aggregation.marketReference.minPrice)}/kg</div></div><div className="rounded-xl bg-[#f7fbf3] p-4"><div className="text-xs text-[#819087]">Modal reference</div><div className="mt-1 font-bold text-[#28623f]">{money(data.aggregation.marketReference.modalPrice)}/kg</div></div><div className="rounded-xl bg-[#f7fbf3] p-4"><div className="text-xs text-[#819087]">Max reference</div><div className="mt-1 font-bold text-[#294c38]">{money(data.aggregation.marketReference.maxPrice)}/kg</div></div></div>}</Surface>

      <Surface className="mt-8 border-l-4 border-l-[#6f9b63] p-6"><div className="flex items-start gap-3"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-[#6f9b63]" /><div><div className="text-xs font-bold uppercase tracking-[0.15em] text-[#6b8f60]">DEMO MODE · NO WRITE OPERATIONS</div><h2 className="mt-2 text-xl font-bold text-[#18332a]">What this walkthrough demonstrates</h2><p className="mt-2 text-sm leading-7 text-[#5f7465]">Farmer supply, buyer demand, deterministic matching, distance and transport estimates, market context, recommendation explanations, and aggregation alternatives. All names, prices, locations, and outcomes are sample data.</p><div className="mt-5 flex flex-wrap gap-3"><ActionButton href="/how-it-works" variant="secondary">Read how it works <ArrowRight size={15} /></ActionButton><ActionButton href="/about" variant="secondary">About FarmConnect <ArrowRight size={15} /></ActionButton></div></div></div></Surface>
      <p className="mt-6 text-center text-xs text-[#819087]">DEMO MODE · SAMPLE DATA · Deterministic estimates · No browser location requested · No persistent changes</p>
    </>}
  </div>;
}
