import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, Check, CircleHelp, IndianRupee, MapPin, Route, Sprout, Truck, Users, X } from "lucide-react";
import { demoMarketSnapshot } from "@/data/demoData";
import { ActionButton, AlertBanner, Eyebrow } from "@/components/farmconnect/DesignSystem";
import { trpc } from "@/lib/trpc";

const decisionSteps = [
  { icon: Sprout, label: "Farmer supply", text: "Crop, quantity and location" },
  { icon: MapPin, label: "Distance", text: "Where the opportunity sits" },
  { icon: Truck, label: "Logistics", text: "Transport and route burden" },
  { icon: Check, label: "Selling outcome", text: "A decision you can explain" },
];

const contributingFarms = [
  { label: "Farm 01", quantity: "700 kg", width: "w-[18%]", tone: "bg-[#6f9b63]" },
  { label: "Farm 02", quantity: "1,000 kg", width: "w-[27%]", tone: "bg-[#86a96d]" },
  { label: "Farm 03", quantity: "2,500 kg", width: "w-[55%]", tone: "bg-[#b9653e]" },
  { label: "Farm 04", quantity: "3,000 kg", width: "w-[66%]", tone: "bg-[#176b45]" },
  { label: "Farm 05", quantity: "2,800 kg", width: "w-[61%]", tone: "bg-[#557a83]" },
];

export default function Home() {
  const [showDemo, setShowDemo] = useState(false);
  const snapshotQuery = trpc.market.demoSnapshot.useQuery();
  const snapshot = snapshotQuery.data ?? demoMarketSnapshot;

  return <>
    <section className="relative overflow-hidden border-b border-[#dde6dc] bg-[#f7f7f1]">
      <div className="container relative grid gap-14 py-14 sm:py-20 lg:grid-cols-[0.88fr_1.12fr] lg:items-center lg:gap-16 lg:py-24">
        <div className="relative z-10 animate-fade-up">
          <div className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-[#6f9b63]"><span className="h-px w-8 bg-[#6f9b63]" />Decision support for Indian agriculture</div>
          <h1 className="max-w-xl text-[2.8rem] font-bold leading-[1.06] tracking-[-0.065em] text-[#17352b] sm:text-6xl">The route to market matters as much as the price.</h1>
          <p className="mt-6 max-w-lg text-base leading-8 text-[#53665b] sm:text-lg">FarmConnect helps farmers and buyers see the complete path: crop, quantity, distance, transport, market reference and the selling outcome.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><ActionButton href="/farmer/produce" size="lg">List your produce <ArrowRight size={17} /></ActionButton><ActionButton href="/buyer" variant="secondary" size="lg">Describe a requirement</ActionButton></div>
          <div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#819087]"><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-[#176b45]" />Transparent factors</span><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-[#176b45]" />Mobile-first workflow</span></div>
        </div>

        <div className="relative animate-fade-up-delay">
          <div className="mb-4 flex items-center justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#819087]">Illustrative decision path</div><div className="mt-1 text-sm font-bold text-[#17352b]">Tomatoes · 850 kg from Pune</div></div><span className="border border-[#d9e5d1] bg-[#eef4e8] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-[#176b45]">Demo context</span></div>
          <div className="relative overflow-hidden border border-[#d7e2d6] bg-[#fffdf8] shadow-[0_16px_40px_rgba(23,53,43,0.09)]">
            <div className="grid grid-cols-2 border-b border-[#e1e8df] bg-[#f7f7f1] sm:grid-cols-5"><div className="flex items-center gap-2 border-b border-[#e1e8df] px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#176b45] sm:border-b-0 sm:border-r"><Sprout size={13} />Farmer supply</div><div className="flex items-center gap-2 border-b border-[#e1e8df] px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#557a83] sm:border-b-0 sm:border-r"><ArrowRight size={13} />Location</div><div className="flex items-center gap-2 border-b border-[#e1e8df] px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#b9653e] sm:border-b-0 sm:border-r"><Truck size={13} />Logistics</div><div className="flex items-center gap-2 border-b border-[#e1e8df] px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#c28a2c] sm:border-b-0 sm:border-r"><Users size={13} />Buyer</div><div className="flex items-center gap-2 px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#176b45] sm:col-span-1"><ArrowRight size={13} />Outcome</div></div><div className="grid divide-y divide-[#e1e8df] md:grid-cols-[1fr_0.8fr_1fr] md:divide-x md:divide-y-0">
              <div className="p-5 sm:p-6"><div className="mb-10 flex h-10 w-10 items-center justify-center bg-[#e6f0de] text-[#176b45]"><Sprout size={20} /></div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#819087]">Farmer supply</div><div className="mt-2 font-heading text-3xl font-bold tracking-[-0.04em] text-[#17352b]">850 kg</div><div className="mt-1 text-sm text-[#53665b]">Tomatoes · Pune</div></div>
              <div className="relative flex flex-col justify-center gap-5 p-5 sm:p-6"><div className="hidden items-center justify-center md:flex"><span className="h-px w-full bg-[#b8cbb4]" /><span className="-ml-1 border-y-[5px] border-l-[7px] border-y-transparent border-l-[#6f9b63]" /></div><div className="flex items-center gap-3 text-sm text-[#53665b]"><MapPin size={17} className="shrink-0 text-[#557a83]" /><span><strong className="block text-[#17352b]">18 km</strong>to a compatible buyer</span></div><div className="flex items-center gap-3 text-sm text-[#53665b]"><Truck size={17} className="shrink-0 text-[#b9653e]" /><span><strong className="block text-[#17352b]">₹1,260</strong>estimated transport</span></div></div>
              <div className="flex flex-col justify-between bg-[#17352b] p-5 text-[#fffdf8] sm:p-6"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#b9d7a1]">Selling outcome</div><div className="mt-3 text-sm text-[#d6e4d1]">Sahyadri Fresh Markets</div><div className="mt-4 font-heading text-3xl font-bold tracking-[-0.04em]">₹19,140</div><div className="mt-1 text-xs text-[#b9cdb9]">after illustrative transport cost</div></div><div className="mt-8 border-t border-white/15 pt-4 text-xs leading-5 text-[#c3d4c1]">A better path is not always the highest visible price.</div></div>
            </div>
            <div className="flex items-center gap-3 border-t border-[#e1e8df] bg-[#f7f7f1] px-5 py-4 text-xs font-semibold text-[#53665b] sm:px-6"><Route size={16} className="text-[#6f9b63]" /><span>Price + distance + logistics + quantity fit</span><ArrowRight size={14} className="ml-auto text-[#819087]" /></div>
          </div>
        </div>
      </div>
    </section>

    <section className="container py-16 sm:py-20"><div className="grid gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><Eyebrow icon={<CircleHelp size={14} />}>What FarmConnect considers</Eyebrow><h2 className="max-w-lg text-3xl font-bold tracking-[-0.045em] text-[#17352b] sm:text-4xl">A selling decision is a connected set of trade-offs.</h2></div><p className="max-w-xl text-sm leading-7 text-[#53665b]">Instead of stopping at buyer discovery, FarmConnect makes the route and its consequences visible before you commit.</p></div><div className="mt-12 grid border-y border-[#dde6dc] sm:grid-cols-2 lg:grid-cols-4">{decisionSteps.map((step, index) => { const Icon = step.icon; return <div key={step.label} className="relative border-b border-[#dde6dc] p-5 last:border-b-0 sm:nth-[2n]:border-l lg:border-b-0 lg:border-l lg:first:border-l-0"><div className="flex items-center justify-between"><Icon size={19} className={index === 1 ? "text-[#557a83]" : index === 2 ? "text-[#b9653e]" : "text-[#176b45]"} /><span className="font-heading text-2xl font-bold text-[#d7e2d6]">0{index + 1}</span></div><h3 className="mt-8 font-bold text-[#17352b]">{step.label}</h3><p className="mt-1 text-sm leading-6 text-[#819087]">{step.text}</p></div>; })}</div></section>

    <section className="border-y border-[#e1d8c9] bg-[#f4eee3]"><div className="container grid gap-12 py-16 sm:py-20 lg:grid-cols-[0.78fr_1.22fr] lg:items-center"><div><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#b9653e]"><Users size={15} /> Collective fulfilment</div><h2 className="max-w-xl text-3xl font-bold tracking-[-0.045em] text-[#17352b] sm:text-4xl">Small farms can become one coordinated fulfilment.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#53665b]">When a buyer needs more than one farm can supply, FarmConnect can make compatible quantities, locations and contributions visible together.</p><Link href="/aggregation" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#176b45] hover:gap-3">Explore aggregation <ArrowRight size={16} /></Link></div><div className="border border-[#dfd3c1] bg-[#fffdf8] p-5 shadow-[0_8px_24px_rgba(112,79,38,0.06)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-[#e9e0d3] pb-5"><div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#b9653e]">Illustrative example</div><div className="mt-2 font-heading text-2xl font-bold tracking-[-0.04em] text-[#17352b]">Buyer requirement · 10,000 kg tomatoes</div></div><div className="text-right"><div className="font-heading text-2xl font-bold text-[#176b45]">10,000 kg</div><div className="text-xs text-[#819087]">potentially fulfilled</div></div></div><div className="relative mt-6 space-y-3"><div className="pointer-events-none absolute bottom-4 right-10 top-4 w-px bg-[#cddbc8]" />{contributingFarms.map(farm => <div key={farm.label} className="relative flex items-center gap-3"><div className="w-16 shrink-0 text-[11px] font-bold text-[#819087]">{farm.label}</div><div className="relative h-8 flex-1 bg-[#f3f0e9]"><div className={`h-full ${farm.width} ${farm.tone}`} /><span className="absolute inset-y-0 left-3 flex items-center text-[11px] font-bold text-white">{farm.quantity}</span></div><ArrowRight size={15} className="relative z-10 shrink-0 text-[#819087]" /></div>)}</div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-[#e9e0d3] pt-5 sm:grid-cols-3"><div><div className="font-heading text-xl font-bold text-[#17352b]">5 farms</div><div className="text-xs text-[#819087]">contributing</div></div><div><div className="font-heading text-xl font-bold text-[#17352b]">1 route</div><div className="text-xs text-[#819087]">coordinated fulfilment</div></div><div className="col-span-2 sm:col-span-1"><div className="font-heading text-xl font-bold text-[#176b45]">Visible fit</div><div className="text-xs text-[#819087]">not a marketplace statistic</div></div></div></div></div></section>

    <section className="container py-16 sm:py-20"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><div className="mb-4 text-xs font-bold uppercase tracking-[0.18em] text-[#6f9b63]">Explainable intelligence</div><h2 className="max-w-2xl text-3xl font-bold tracking-[-0.045em] text-[#17352b] sm:text-4xl">AI helps organize the decision. The factors stay visible.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#53665b]">Every recommendation should be legible to the people making the call. FarmConnect keeps the explanation close to the match.</p></div><div className="border-l-2 border-[#d7e2d6] pl-6 sm:pl-8"><div className="space-y-4 text-sm text-[#53665b]"><div className="flex items-center gap-3"><span className="h-2 w-2 bg-[#176b45]" />Crop compatibility</div><div className="flex items-center gap-3"><span className="h-2 w-2 bg-[#6f9b63]" />Quantity fit and partial fulfilment</div><div className="flex items-center gap-3"><span className="h-2 w-2 bg-[#557a83]" />Distance and route context</div><div className="flex items-center gap-3"><span className="h-2 w-2 bg-[#b9653e]" />Transport burden</div><div className="flex items-center gap-3"><span className="h-2 w-2 bg-[#c28a2c]" />Market reference and offered price</div></div></div></div></section>

    <section className="container pb-16 sm:pb-20"><div className="border-t-4 border-[#176b45] bg-[#17352b] p-7 text-[#fffdf8] sm:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-[#b9d7a1]">Choose your starting point</div><h2 className="max-w-xl text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Start with the decision in front of you.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#c3d4c1]">List produce, describe a buyer requirement, and make the relevant route visible.</p></div><div className="flex flex-col gap-3 sm:flex-row"><ActionButton href="/farmer/produce" variant="secondary" size="lg" className="w-fit border-white/20 bg-white/10 text-white hover:bg-white hover:text-[#17352b]">I am a farmer <ArrowRight size={17} /></ActionButton><ActionButton href="/buyer" variant="secondary" size="lg" className="w-fit border-white/20 bg-white/10 text-white hover:bg-white hover:text-[#17352b]">I am a buyer <ArrowRight size={17} /></ActionButton></div></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-[#819087]">Demo context is labeled; market references include source and timestamp.</p><button onClick={() => setShowDemo(true)} className="inline-flex items-center gap-2 text-xs font-bold text-[#176b45] hover:text-[#17352b]">View demo data <ArrowRight size={14} /></button></div></section>

    {showDemo && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#17352b]/40 p-4 backdrop-blur-sm sm:items-center"><div role="dialog" aria-modal="true" aria-labelledby="demo-data-title" className="w-full max-w-lg border border-[#d7e2d6] bg-[#fffdf8] p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><Eyebrow icon={<Sprout size={14} />}>Transparent by design</Eyebrow><h2 id="demo-data-title" className="font-heading text-2xl font-bold tracking-[-0.04em] text-[#17352b]">Demo market snapshot</h2></div><button aria-label="Close demo data" onClick={() => setShowDemo(false)} className="p-2 text-[#819087] hover:bg-[#e6f0de] hover:text-[#176b45]"><X size={18} /></button></div><div className="mt-4"><AlertBanner tone="info">This foundation uses realistic seed data so the product is usable without external credentials. No match ranking is performed in Phase 1.</AlertBanner></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="bg-[#f4f6ee] p-4"><div className="font-heading text-2xl font-bold text-[#17352b]">{snapshot.farmers.length}</div><div className="mt-1 text-xs text-[#819087]">demo farmer profiles</div></div><div className="bg-[#f4f6ee] p-4"><div className="font-heading text-2xl font-bold text-[#17352b]">{snapshot.buyers.length}</div><div className="mt-1 text-xs text-[#819087]">demo buyer profiles</div></div></div><div className="mt-5 flex justify-end"><ActionButton onClick={() => setShowDemo(false)} variant="dark">Close</ActionButton></div></div></div>}
  </>;
}
