import { Calculator, CheckCircle2, Map, Scale, Sprout, Truck } from "lucide-react";
import { Link } from "wouter";
import { ActionButton, AlertBanner, Eyebrow, PageHeader, Surface } from "@/components/farmconnect/DesignSystem";

const principles = [{ icon: Sprout, title: "Start with real context", text: "Crop, quantity, location and your price floor create the starting point." }, { icon: Map, title: "Understand distance", text: "Nearby and farther buyers can lead to very different outcomes once travel is included." }, { icon: Truck, title: "Estimate logistics", text: "A configurable transport service will make cost assumptions visible instead of hiding them." }, { icon: Calculator, title: "Compare the outcome", text: "Deterministic business logic handles arithmetic — never a language model." }, { icon: Scale, title: "Explain the recommendation", text: "The final path should tell you why it is a better fit, not just show a score." }, { icon: CheckCircle2, title: "Keep you in control", text: "Farmers and buyers make the final decision with the trade-offs in front of them." }];

export default function HowItWorks() {
  return <div className="container py-10 sm:py-16"><PageHeader eyebrow="The FarmConnect method" title="A smarter selling path is more than a better price." description="FarmConnect is being designed to make the full opportunity visible — from the farm gate to the buyer’s requirement." action={<ActionButton href="/farmer/produce">Try the foundation</ActionButton>} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{principles.map(({ icon: Icon, title, text }, index) => <Surface key={title} className="p-6"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eff8e9] text-[#39704d]"><Icon size={19} /></span><span className="text-2xl font-bold tracking-[-0.06em] text-[#e5eee0]">0{index + 1}</span></div><h2 className="mt-7 font-bold text-[#294c38]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#718274]">{text}</p></Surface>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><Surface className="p-6 sm:p-8" accent><Eyebrow icon={<Scale size={14} />}>What FarmConnect will never do</Eyebrow><h2 className="text-2xl font-bold tracking-[-0.04em] text-[#18332a]">Hide the assumptions behind a recommendation.</h2><div className="mt-5 space-y-3 text-sm leading-6 text-[#5f7465]"><div className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6b9b57]" />No ranking arithmetic delegated to AI.</div><div className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6b9b57]" />No pretend live map or transport response.</div><div className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6b9b57]" />No highest-price-only recommendations.</div></div></Surface><Surface className="p-6 sm:p-8"><div className="text-xs font-bold uppercase tracking-[0.14em] text-[#6b8f60]">Phase 1 status</div><h2 className="mt-3 text-2xl font-bold tracking-[-0.04em] text-[#18332a]">The foundation is live.</h2><p className="mt-3 text-sm leading-6 text-[#718274]">You can explore the farmer and buyer flows, create demo listings and move through the route boundaries. Deterministic matching is intentionally next.</p><AlertBanner tone="success">Architecture ready for the calculation layer.</AlertBanner><Link href="/about" className="mt-5 inline-flex text-sm font-bold text-[#1b5e3c] hover:underline">Why this matters <span className="ml-2">→</span></Link></Surface></div></div>;
}
