import { AlertTriangle, CheckCircle2, Clock3, Info, Loader2, TrendingDown, TrendingUp } from "lucide-react";
import { AlertBanner, BadgePill, Surface } from "@/components/farmconnect/DesignSystem";
import { trpc } from "@/lib/trpc";
import type { Crop } from "@shared/types";

function formatObserved(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

export default function MarketReferenceCard({ crop, location, expectedPrice }: { crop?: Crop; location: string; expectedPrice?: number }) {
  const enabled = Boolean(crop && location.trim().length >= 2);
  const query = trpc.marketPrices.reference.useQuery({ crop: crop ?? "Tomatoes", location: location.trim() }, { enabled, staleTime: 60_000 });
  if (!crop) return <Surface className="p-5"><div className="flex items-center gap-2 text-sm font-bold text-[#856117]"><Info size={16} /> Choose a supported crop to see market context.</div><p className="mt-2 text-xs leading-5 text-[#718274]">This reference is only shown for supported crops and never replaces FarmConnect’s matching calculations.</p></Surface>;
  if (!enabled) return <Surface className="p-5"><div className="flex items-center gap-2 text-sm font-bold text-[#294c38]"><Info size={16} /> Add a location to see market context.</div><p className="mt-2 text-xs leading-5 text-[#718274]">This is reference information only and never replaces FarmConnect’s matching calculations.</p></Surface>;
  if (query.isLoading) return <Surface className="p-5"><div className="flex items-center gap-2 text-sm text-[#5f7465]"><Loader2 size={16} className="animate-spin" /> Loading market reference…</div></Surface>;
  if (query.error) return <Surface className="p-5"><AlertBanner tone="warning"><strong>Market reference unavailable.</strong> Your listing flow still works. Try again when the source is available.</AlertBanner><button type="button" onClick={() => query.refetch()} className="mt-3 text-xs font-bold text-[#1b5e3c] underline underline-offset-2">Retry market reference</button></Surface>;
  const reference = query.data;
  if (!reference || reference.status === "unavailable") return <Surface className="p-5"><div className="flex items-center gap-2 text-sm font-bold text-[#856117]"><AlertTriangle size={16} /> Live market price unavailable</div><p className="mt-2 text-xs leading-5 text-[#718274]">{reference?.message ?? "No market result is available for this location."}</p></Surface>;
  const withinRange = expectedPrice !== undefined && expectedPrice >= reference.minPrice && expectedPrice <= reference.maxPrice;
  const belowRange = expectedPrice !== undefined && expectedPrice < reference.minPrice;
  return <Surface className="p-5" accent={reference.status === "demo"}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><BadgePill tone={reference.isLive ? "green" : "amber"}>{reference.isLive ? <><CheckCircle2 size={13} /> Live reference</> : <><Info size={13} /> Market reference — demo data</>}</BadgePill><span className="text-xs text-[#819086]">{reference.location}</span></div><h3 className="mt-3 text-lg font-bold text-[#18332a]">{reference.crop} indicative range</h3></div><div className="rounded-2xl bg-white px-4 py-3 text-right"><div className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#8a9a8d]">Modal reference</div><div className="mt-1 text-xl font-bold text-[#28623f]">₹{reference.modalPrice}/kg</div></div></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white p-3"><div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#8a9a8d]">Min</div><div className="mt-1 font-bold text-[#294c38]">₹{reference.minPrice}</div></div><div className="rounded-2xl bg-white p-3"><div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#8a9a8d]">Modal</div><div className="mt-1 font-bold text-[#294c38]">₹{reference.modalPrice}</div></div><div className="rounded-2xl bg-white p-3"><div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#8a9a8d]">Max</div><div className="mt-1 font-bold text-[#294c38]">₹{reference.maxPrice}</div></div></div>{expectedPrice !== undefined && <div className={`mt-4 flex items-start gap-2 rounded-2xl p-3 text-xs leading-5 ${withinRange ? "bg-[#eff8e9] text-[#28623f]" : "bg-[#fffaf0] text-[#856117]"}`}>{withinRange ? <CheckCircle2 size={15} className="mt-0.5 shrink-0" /> : belowRange ? <TrendingDown size={15} className="mt-0.5 shrink-0" /> : <TrendingUp size={15} className="mt-0.5 shrink-0" />}<span><strong>Your expected price: ₹{expectedPrice}/kg.</strong> {withinRange ? "Within recent market range." : belowRange ? "Below the recent indicative range." : "Above the recent indicative range."} This is context, not a guaranteed selling price.</span></div>}<div className="mt-4 flex flex-col gap-1 text-[11px] leading-5 text-[#819086] sm:flex-row sm:items-center sm:justify-between"><span className="inline-flex items-center gap-1.5"><Info size={12} />Source: {reference.source}</span><span className="inline-flex items-center gap-1.5"><Clock3 size={12} />Observed: {formatObserved(reference.observedAt)}</span></div><p className="mt-2 text-[11px] leading-5 text-[#819086]">{reference.message}</p></Surface>;
}
